In [1]:
import numpy as np


In [3]:
# create array , matrix
a = np.array([1, 2, 3, 4, 5])
 

In [4]:
a

array([1, 2, 3, 4, 5])

In [6]:
b = np.array([[1, 2], [3,4]])

In [7]:
b

array([[1, 2],
       [3, 4]])

In [8]:
#shape
print(a.shape, b.shape)

(5,) (2, 2)


In [9]:
#reshape
c = a.reshape((5, 1))
c.shape

(5, 1)

In [15]:
d = a.reshape((5, -1, 1))

In [12]:
d

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])

In [13]:
d.shape

(5, 1, 1)

In [14]:
g =np.array([[5, 6]])
g

array([[5, 6]])

In [16]:
# concatenate

a = np.array([1, 2 ,3])

b = np.array([4, 5])

c = np.concatenate((a , b))

In [17]:
c

array([1, 2, 3, 4, 5])

In [20]:
c = np.array([10])

c

array([10])

In [21]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

a.shape

(9,)

In [24]:
b = a[2: 8: 2]

In [25]:
b

array([3, 5, 7])

In [26]:
a = np.array([1, 2, 3])
b = np.array([4,5,6])
c = np.vstack((a, b))

c

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
c.shape

(2, 3)

In [28]:
c = np.hstack((a , b))

In [29]:
c

array([1, 2, 3, 4, 5, 6])

In [31]:
#normalize
mean_a = np.mean(a)
mean_a


np.float64(2.0)

In [32]:
std_a = np.std(a)
std_a

np.float64(0.816496580927726)

In [33]:
norm_a =(a - mean_a)/std_a
norm_a

array([-1.22474487,  0.        ,  1.22474487])

In [35]:
np.mean(norm_a)

np.float64(0.0)